use proc_macro2::{Span, TokenStream};

pub fn format(tokens: proc_macro::TokenStream) -> TokenStream {
    match try_format(tokens) {
        Ok(output) => output,
        Err(err) => err.to_compile_error(),
    }
}

fn try_format(tokens: proc_macro::TokenStream) -> Result<TokenStream, syn::Error> {
    let ident = tokens.to_string();

    let output = match &*ident {
        "r8unorm" | "R8Unorm" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "r8snorm" | "R8Snorm" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "r8uscaled" | "R8Uscaled" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "r8sscaled" | "R8Sscaled" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "r8uint" | "R8Uint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "r8sint" | "R8Sint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "r8srgb" | "R8Srgb" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "rg8unorm" | "RG8Unorm" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "rg8snorm" | "RG8Snorm" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "rg8uscaled" | "RG8Uscaled" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "rg8sscaled" | "RG8Sscaled" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "rg8uint" | "RG8Uint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "rg8sint" | "RG8Sint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "rg8srgb" | "RG8Srgb" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "rgb8unorm" | "RGB8Unorm" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "rgb8snorm" | "RGB8Snorm" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "rgb8uscaled" | "RGB8Uscaled" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "rgb8sscaled" | "RGB8Sscaled" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "rgb8uint" | "RGB8Uint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "rgb8sint" | "RGB8Sint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "rgb8srgb" | "RGB8Srgb" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "bgr8unorm" | "BGR8Unorm" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "bgr8snorm" | "BGR8Snorm" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "bgr8uscaled" | "BGR8Uscaled" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "bgr8sscaled" | "BGR8Sscaled" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "bgr8uint" | "BGR8Uint" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "bgr8sint" | "BGR8Sint" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "bgr8srgb" | "BGR8Srgb" => "::sierra::FormatDescription<::sierra::RBG, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "rgba8unorm" | "RGBA8Unorm" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "rgba8snorm" | "RGBA8Snorm" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "rgba8uscaled" | "RGBA8Uscaled" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "rgba8sscaled" | "RGBA8Sscaled" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "rgba8uint" | "RGBA8Uint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "rgba8sint" | "RGBA8Sint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "rgba8srgb" | "RGBA8Srgb" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "bgra8unorm" | "BGRA8Unorm" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Unorm>",
        "bgra8snorm" | "BGRA8Snorm" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Snorm>",
        "bgra8uscaled" | "BGRA8Uscaled" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Uscaled>",
        "bgra8sscaled" | "BGRA8Sscaled" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Sscaled>",
        "bgra8uint" | "BGRA8Uint" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "bgra8sint" | "BGRA8Sint" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Sint>",
        "bgra8srgb" | "BGRA8Srgb" => "::sierra::FormatDescription<::sierra::BGRA, ::sierra::ConstBits<8>, ::sierra::Srgb>",
        "r16unorm" | "R16Unorm" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "r16snorm" | "R16Snorm" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Snorm>",
        "r16uscaled" | "R16Uscaled" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Uscaled>",
        "r16sscaled" | "R16Sscaled" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Sscaled>",
        "r16uint" | "R16Uint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Uint>",
        "r16sint" | "R16Sint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Sint>",
        "r16sfloat" | "R16Sfloat" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<16>, ::sierra::Sfloat>",
        "rg16unorm" | "RG16Unorm" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "rg16snorm" | "RG16Snorm" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Snorm>",
        "rg16uscaled" | "RG16Uscaled" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Uscaled>",
        "rg16sscaled" | "RG16Sscaled" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Sscaled>",
        "rg16uint" | "RG16Uint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Uint>",
        "rg16sint" | "RG16Sint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Sint>",
        "rg16sfloat" | "RG16Sfloat" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<16>, ::sierra::Sfloat>",
        "rgb16unorm" | "RGB16Unorm" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "rgb16snorm" | "RGB16Snorm" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Snorm>",
        "rgb16uscaled" | "RGB16Uscaled" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Uscaled>",
        "rgb16sscaled" | "RGB16Sscaled" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Sscaled>",
        "rgb16uint" | "RGB16Uint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Uint>",
        "rgb16sint" | "RGB16Sint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Sint>",
        "rgb16sfloat" | "RGB16Sfloat" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<16>, ::sierra::Sfloat>",
        "rgba16unorm" | "RGBA16Unorm" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "rgba16snorm" | "RGBA16Snorm" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Snorm>",
        "rgba16uscaled" | "RGBA16Uscaled" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Uscaled>",
        "rgba16sscaled" | "RGBA16Sscaled" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Sscaled>",
        "rgba16uint" | "RGBA16Uint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Uint>",
        "rgba16sint" | "RGBA16Sint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Sint>",
        "rgba16sfloat" | "RGBA16Sfloat" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<16>, ::sierra::Sfloat>",
        "r32uint" | "R32Uint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<32>, ::sierra::Uint>",
        "r32sint" | "R32Sint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<32>, ::sierra::Sint>",
        "r32sfloat" | "R32Sfloat" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        "rg32uint" | "RG32Uint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<32>, ::sierra::Uint>",
        "rg32sint" | "RG32Sint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<32>, ::sierra::Sint>",
        "rg32sfloat" | "RG32Sfloat" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        "rgb32uint" | "RGB32Uint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<32>, ::sierra::Uint>",
        "rgb32sint" | "RGB32Sint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<32>, ::sierra::Sint>",
        "rgb32sfloat" | "RGB32Sfloat" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        "rgba32uint" | "RGBA32Uint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<32>, ::sierra::Uint>",
        "rgba32sint" | "RGBA32Sint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<32>, ::sierra::Sint>",
        "rgba32sfloat" | "RGBA32Sfloat" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        "r64uint" | "R64Uint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<64>, ::sierra::Uint>",
        "r64sint" | "R64Sint" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<64>, ::sierra::Sint>",
        "r64sfloat" | "R64Sfloat" => "::sierra::FormatDescription<::sierra::R, ::sierra::ConstBits<64>, ::sierra::Sfloat>",
        "rg64uint" | "RG64Uint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<64>, ::sierra::Uint>",
        "rg64sint" | "RG64Sint" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<64>, ::sierra::Sint>",
        "rg64sfloat" | "RG64Sfloat" => "::sierra::FormatDescription<::sierra::RG, ::sierra::ConstBits<64>, ::sierra::Sfloat>",
        "rgb64uint" | "RGB64Uint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<64>, ::sierra::Uint>",
        "rgb64sint" | "RGB64Sint" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<64>, ::sierra::Sint>",
        "rgb64sfloat" | "RGB64Sfloat" => "::sierra::FormatDescription<::sierra::RGB, ::sierra::ConstBits<64>, ::sierra::Sfloat>",
        "rgba64uint" | "RGBA64Uint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<64>, ::sierra::Uint>",
        "rgba64sint" | "RGBA64Sint" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<64>, ::sierra::Sint>",
        "rgba64sfloat" | "RGBA64Sfloat" => "::sierra::FormatDescription<::sierra::RGBA, ::sierra::ConstBits<64>, ::sierra::Sfloat>",
        "d16unorm" | "D16Unorm" => "::sierra::FormatDescription<::sierra::D, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "d32sfloat" | "D32Sfloat" => "::sierra::FormatDescription<::sierra::D, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        "s8uint" | "S8Uint" => "::sierra::FormatDescription<::sierra::S, ::sierra::ConstBits<8>, ::sierra::Uint>",
        "d16unorms8uint" | "D16UnormS8Uint" => "::sierra::FormatDescription<::sierra::DS, ::sierra::ConstBits<16>, ::sierra::Unorm>",
        "d24unorms8uint" | "D24UnormS8Uint" => "::sierra::FormatDescription<::sierra::DS, ::sierra::ConstBits<24>, ::sierra::Unorm>",
        "d32sfloats8uint" | "D32SfloatS8Uint" => "::sierra::FormatDescription<::sierra::DS, ::sierra::ConstBits<32>, ::sierra::Sfloat>",
        _ => return Err(syn::Error::new(Span::call_site(), "Unrecognized format")),
    };

    Ok(output.parse().unwrap())
}
