[package]
name = "sierra-proc-demo"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"

[dependencies]
sierra = { version = "0.1.0", path = ".." }
sierra-proc = { version = "0.1.0", path = "../proc", features = ["verbose-docs"] }
